# Use an official Node.js runtime as the base image
FROM node:18

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json (if available)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Install Dapr CLI
# RUN curl -fsSL https://raw.githubusercontent.com/dapr/cli/master/install/install.sh | /bin/bash

# Expose the port
EXPOSE 3002

# Command to run the app
# CMD ["dapr", "run", "--app-id", "notification-service", "--app-port", "3002", "--components-path", "/components", "--", "node", "index.js"]
CMD [ "node", "index.js" ]